### ISSUE TITLE
For v4.6.0

### ISSUE THREAD

**Issue by yusukebe** [honojs/website#478]
- [x] feat(secureHeader): add Permissions-Policy header to secure headers middleware [#3314] https://github.com/honojs/website/pull/476(https://github.com/honojs/hono/pull/3314)
- [x] feat(cloudflare-pages): enable `c.env.eventContext` in handleMiddleware [#3332](https://github.com/honojs/hono/pull/3332) https://github.com/honojs/website/pull/479
- [x] feat(websocket): Add generics type to `WSContext` [#3337](https://github.com/honojs/hono/pull/3337) https://github.com/honojs/website/pull/480
- [x] feat(jsx-renderer): set `Content-Encoding` when `stream` is true [#3355](https://github.com/honojs/hono/pull/3355) https://github.com/honojs/website/pull/481
- [x] feat(contextStorage): added Context Storage Middleware [#3373](https://github.com/honojs/hono/pull/3373) https://github.com/honojs/website/pull/463
- [x] feat(serveStatic): add `precompressed` option [#3366](https://github.com/honojs/hono/pull/3366) https://github.com/honojs/website/pull/484
- [x] ~~feat(helper/streaming): Support `Promise<string>` or (async) `JSX.Element` in `streamSSE` [#3344](https://github.com/honojs/hono/pull/3344)~~
- [x] ~~feat(context): make fetch Response headers mutable [#3318](https://github.com/honojs/hono/pull/3318)~~
- [x] feat(serve-static): add `onFound` option [#3396](https://github.com/honojs/hono/pull/3396) https://github.com/honojs/website/pull/485
- [x] feat(basic-auth): added custom response message option [#3371](https://github.com/honojs/hono/pull/3371) https://github.com/honojs/website/pull/486
- [x] feat(bearer-auth): added custom response message options [#3372](https://github.com/honojs/hono/pull/3372) https://github.com/honojs/website/pull/486
